# Generated by Django 3.2.25 on 2024-03-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='atu_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ATU number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='company name'),
        ),
    ]
