# Generated by Django 3.2.25 on 2024-03-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('privat', 'Privat'), ('business', 'Business')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
