# Generated by Django 3.2.25 on 2024-03-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20240326_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
    ]
