# Generated by Django 3.2.25 on 2024-03-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default=1, max_length=150, verbose_name='full address'),
            preserve_default=False,
        ),
    ]
