# Generated by Django 3.2.25 on 2024-04-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customize',
            field=models.BooleanField(default=False, verbose_name='Customize'),
        ),
    ]
