# Generated by Django 3.2.25 on 2024-04-02 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_product_customize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productingredient',
            name='ingredient_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='base.ProductIngredient'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='base.product'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
