# Generated by Django 3.2.25 on 2024-04-02 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20240402_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ingredient'),
        ),
    ]
