# Generated by Django 3.2.25 on 2024-04-02 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_productingredient_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='IngredientUserCustomize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_customized', to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ingredients_customized',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='base.IngredientUserCustomize'),
        ),
    ]
