# Generated by Django 3.2.25 on 2024-04-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20240402_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ingredients_customized',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_items', to='base.IngredientUserCustomize'),
        ),
    ]
