# Generated by Django 3.2.25 on 2024-04-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_orderitem_ingredients_customized'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ingredients_customized',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='base.IngredientUserCustomize'),
        ),
    ]
