# Generated by Django 5.0.4 on 2024-05-11 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20240409_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientusercustomize',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity in kg'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity in kg'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_total', models.FloatField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
