# Generated by Django 5.0.4 on 2024-05-11 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_ingredientusercustomize_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscription_total',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_type', models.CharField(choices=[('active', 'Active'), ('non active', 'Non Active'), ('one time purchase', 'One Time Purchase')], max_length=255)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
