# Generated by Django 5.0.4 on 2024-05-23 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_usersubscription_subscription_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing'), ('delivery', 'Delivery')], default='billing', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezirk', models.CharField(max_length=255, verbose_name='bezirk')),
                ('street_address', models.CharField(max_length=255, verbose_name='street address')),
                ('hausnummer', models.CharField(max_length=255, verbose_name='hausnummer')),
                ('plz_zip', models.CharField(max_length=255, verbose_name='postal code')),
                ('additional_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='additional info')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
