# Generated by Django 5.0.4 on 2024-05-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_customuser_address_type_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='phone_number',
            field=models.CharField(default=0, max_length=255, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
