# Generated by Django 5.0.4 on 2024-05-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactiveCompanyUser',
            fields=[
            ],
            options={
                'verbose_name': 'Inactive Company User',
                'verbose_name_plural': 'Inactive Company Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.customuser',),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subscription_type',
            field=models.CharField(choices=[('active', 'Active'), ('non active', 'Non Active'), ('one time purchase', 'One Time Purchase'), ('cash', 'Cash')], max_length=255),
        ),
    ]
