# Generated by Django 5.0.4 on 2024-05-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_inactivecompanyuser_product_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address_type',
            field=models.CharField(blank=True, choices=[('billing', 'Billing'), ('delivery', 'Delivery')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='base.order'),
        ),
    ]
