# Generated by Django 5.0.4 on 2024-05-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_order_delivery_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_period',
            new_name='delivery_frequency',
        ),
    ]
