# Generated by Django 5.0.4 on 2024-06-02 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_rename_delivery_period_order_delivery_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Subscription Order',
                'verbose_name_plural': 'Subscription Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.order',),
        ),
    ]
